//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 12:13:42 PM CEST 
//


package com.socgen.sgi.xmpinjection.consummer.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for metadonneesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="metadonneesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="metadonneesEnsemble" type="{http://benchresources.in/entities/sgi}metadonneesEnsembleType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metadonneesType", propOrder = {
    "metadonneesEnsemble"
})
public class MetadonneesType {

    @XmlElement(required = true)
    protected List<MetadonneesEnsembleType> metadonneesEnsemble;

    /**
     * Gets the value of the metadonneesEnsemble property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadonneesEnsemble property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadonneesEnsemble().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadonneesEnsembleType }
     * 
     * 
     */
    public List<MetadonneesEnsembleType> getMetadonneesEnsemble() {
        if (metadonneesEnsemble == null) {
            metadonneesEnsemble = new ArrayList<MetadonneesEnsembleType>();
        }
        return this.metadonneesEnsemble;
    }

	@Override
	public String toString() {
		return "MetadonneesType [metadonneesEnsemble=" + metadonneesEnsemble + "]";
	}
}
